function DoMy_Conn_Coh(sFiles, TimeWin)

% Start a new report
bst_report('Start', sFiles);

% Process: Coherence NxN
sFiles = bst_process('CallProcess', 'process_cohere1n', sFiles, [], ...
    'timewindow',   TimeWin, ...
    'dest_sensors', 'EEG', ...
    'includebad',   1, ...
    'removeevoked', 0, ...
    'cohmeasure',   'mscohere', ...  % Magnitude-squared Coherence|C|^2 = |Gxy|^2/(Gxx*Gyy)
    'overlap',      50, ...
    'maxfreqres',   2, ...
    'maxfreq',      40, ...
    'outputmode',   1);  % Save individual results (one file per input file)


% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);



end